spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentdb
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: StudentService

server:
  port: 9090